debug = false
timeout = 250
multiclient_limit = 16
max_chars = 256
zalgo_tolerance = 3


[general]
hostname = "<dollar>H"
playerlimit = 100
port = 27016
local = false
modpass = "mod"
motd = "Welcome to my server!"
use_websockets = true
websocket_port = 50001

[masterserver]
use = true
ip = "master.aceattorneyonline.com"
port = 27016
name = "My server"
description = "My server description!"

[music_change_floodguard]
times_per_interval = 3
interval_length = 20
mute_length = 180

[wtce_floodguard]
times_per_interval = 5
interval_length = 10
mute_length = 1000
